__author__ = 'orish_000'
import calendar

SLIGHTLY_INCONVENIENT = 1
VERY_INCONVENIENT = 2
IMPOSSIBLE = 3
CONSTRAINT_SEVERITIES = [SLIGHTLY_INCONVENIENT, VERY_INCONVENIENT, IMPOSSIBLE]
WEEKDAYS = [calendar.SUNDAY, calendar.MONDAY, calendar.TUESDAY, calendar.WEDNESDAY, calendar.THURSDAY]